# This is an example distribution file for PedSilicoICH simulations
# All parameters are given as a list which is sampled from in the `recruit` program
#
# uncommented parameters here will override defaults
[general]
output_directory="/projects01/didsr-aiml/brandon.nelson/pedsilicoICH/head_experiment/rd"
desired_cases=100  # desired dataset size
keep_raw=false  # keep projection data
seed=42  # seed to reproduce dataset, set to false or integer

[patient]
age=[0, 100]  # range in yrs [min, max]

[lesion]
subtypes=[false]

[acquisition]
views=[1000]
kVp=[120]
mA=[240]

[recon]
kernel=['standard']
slice_thickness=1